package com.example.rev_eshop.model;

public enum ProductCategory {
    BEAUTY,
    FRAGRANCE,
    FURNITURE,
    GROCERIES,
    HOMEDECORATION,
    KITCHENACCESSORIES,
    LAPTOPS,
    MENSSHIRTS,
    MESNSHOES,
    MENSWATCHES,
    MOBILEACCESSSORIES,
    MOTORCYCLE,
    SKINCARE,
    SMARTPHONES,
    SPORTSACCESSORIES,
    SUNGLASSES,
    TABLETS,
    TOPS,
    VEHICLE,
    WOMENSBAGS,
    WOMENSDRESSES,
    WOMENSJEWELLERY,
    WOMENSSHOES,
    WOMENSWATCHES
}
